name: Auto Encrypt Site
on:
  push:
    branches:
      - source # This triggers the script when Publii syncs to 'source'

jobs:
  encrypt-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install StatiCrypt
        run: npm install -g staticrypt

      - name: Run Encryption
        run: |
          staticrypt . -r -p "${{ secrets.STATICRYPT_PASSWORD }}" \
          --remember 30 \
          -d "encrypted-output" \
          --template-color-primary "#6b182f" \
          --template-color-secondary "#6b182f" \
          --template-title "Zettlebank Secure Access" \
          --template-instructions "Checkmark the 'Remember me' box so your browser saves the key for each page as you navigate the site." \
          --no-config

      - name: Deploy to Main Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: ./encrypted-output
