- name: Run Encryption
        run: |
          staticrypt . -r -p "${{ secrets.STATICRYPT_PASSWORD }}" \
          --remember 30 \
          -d "encrypted-output" \
          --template-color-primary "#6b182f" \
          --template-color-secondary "#6b182f" \
          --template-title "Zettlebank Secure Access" \
          --template-instructions "Checkmark the 'Remember me' box so your browser saves the key for each page as you navigate the site."
